---
title: "Workflow"
author: "Ivara Goulden"
date: "2024-10-08"
output: html_document
---

Writing this in markdown so that it doesn't require code comments all the time

Question of interest (data framing)
To what degree the emergence of a periodical cicada brood influences copperhead activity and population, calculated as the percent of iNat snake observations that are eastern copperheads. Similar to the paper 'Periodical Cicada Emergences Affect Masting Behavior of Oaks' want to conduct a superimposed epoch analysis to see the results of periodical cicada emergence on these snakes.

Steps are as follows:

- download iNat data on all snake observations in all years within the range
of the eastern copperhead. 
 Downloaded from GBIF, then filtered to just snakes
 returns 380,000 observations
 So, this should definetely be done through iNat instead, sorry iNat downloader, because there's a LOT of data that is missing from the GBIF filter for squamates. To the tune of 7k copperhead observations, eg GBIF says 11k, iNat says 18k
 For the multi-step iNat download, could double-check that areas weren't missed by also downloading the copperhead data and making sure it's all present in the combined iNat data. (done)
- from the iNat data, want to make sure we don't have duplicate observations. For each species (yes, even outside of copperheads because this affects the % snakes observed that are copperheads) round lat/lon to the nearest .001 and count just unique observations for that day/county/lat-lon/species. (NOT YET DONE)
- download data on the location of periodicial cicada broods (might be available from Koenig et al. 2023) (done)
- filter snake data to within the counties that have periodical cicada broods 
- associate snake location data with a county
- filter both the county, !!!!!!!!!!!!!!!!! AND THE BROOD data !!!!!!!!!!!!!!!!! to counties that have at least one copperhead observation eg. are within the copperhead range. We want to know only within the copperhead range if the emergence of periodical cicadas causes a rise in copperhead observations
- for both each county and each overall brood emergence area, get the proportion of all snake observations that are copperheads in each year (done)
- probably ought to filter to only after 2008 as this is when there are about a thousand snake observations a year, seems like a good minimum bound. If it needs to be moved up, 2013 is the first year over 100 copperheads were observed. 
- Allen comment: just look at recent years, like 2019+ across all the counties, do we see this pattern? Add in the spatial element, it matters
- filter to years where the number of overall snakes observed is at least 20 - this could and likely should be moved up but it's a good lower bound. 
- take a casual look at this data to see if there's anything interesting that looks like it might be going on
- Allen comment: Have an alternative snake comparison, idea is that copperheads are unique amongst the snakes in how they seek and detect prey. Dif btwn cicada yr and non-emergence year, then also that dif for copperheads vs non-hypothesized preador of cicadas -> maybe ratsnake complex -> maybe this is already accounted for by using copperheads as a perc of snakes, being compared to all non-cicada eating snakes already -> maybe still useful as a test!
- run a superimposed epoch analysis - see oak tree paper for citations that reference it's use and how to run it
- graph and check out results
- ?? paper?


-Notes 2025.03.26
Thoughts on copperheads:
-Still need to filter for unique observations where two ppl record the same snake
-County isn't really a unit that matters..so nor does perc county
- the unit that matters is the brood! that's a boundary that's biologically meaningful, and a place you can ask about % copperhead vs % snakes in cicada and non-cicada years
- should do this in a bayesian framework where my predictor is the % of observations in a brood year that are copperheads, fit a different intercept for every brood (they come from different areas with dif expectations about background copperheads), and ask if there's a different effect if cicada yr is 1 (present) or cicada yr is 0. (not present). 
- let's not worry about things like "is there an effect in the next yr" this would be like, from a copperhead population increase in the year following cicadas. That's an interesting question but a secondary one, and the first question is one that's easier to answer, so let's do that first. this second model would be like. Just add another slope for cicada year. Have 3 options instead of binary. 
